/****** Object:  Database [ejercicio]    Script Date: 15/7/2022 18:26:20 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'ejercicio')
BEGIN
CREATE DATABASE [ejercicio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ejercicio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ejercicio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ejercicio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ejercicio_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
END
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ejercicio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ejercicio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ejercicio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ejercicio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ejercicio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ejercicio] SET ARITHABORT OFF 
GO

ALTER DATABASE [ejercicio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ejercicio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ejercicio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ejercicio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ejercicio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ejercicio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ejercicio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ejercicio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ejercicio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ejercicio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ejercicio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ejercicio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ejercicio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ejercicio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ejercicio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ejercicio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ejercicio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ejercicio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ejercicio] SET  MULTI_USER 
GO

ALTER DATABASE [ejercicio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ejercicio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ejercicio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ejercicio] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ejercicio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ejercicio] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ejercicio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ejercicio] SET  READ_WRITE 
GO


